misc: Use stdlib.h instead of malloc.h to make it compile on FreeBSD
/usr/include/malloc.h:3:2: error: #error "<malloc.h> has been replaced by <stdlib.h>"